import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/assets/scss/main.scss";

const iranYekan = localFont({
  src: [
    {
      path: "../assets/fonts/iran-yekan/iran-yekan-regular.ttf",
      weight: "400",
    },
    {
      path: "../assets/fonts/iran-yekan/iran-yekan-bold.ttf",
      weight: "700",
    },
    {
      path: "../assets/fonts/iran-yekan/iran-yekan-black.ttf",
      weight: "900",
    },
  ],
  variable: "--font-iranyekan",
  display: "swap", // Optional, improves loading behavior
});

export const metadata: Metadata = {
  title: "Coinersho",
  description: "Generated by Amin Erfanian",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={iranYekan.variable}>
      <body>{children}</body>
    </html>
  );
}
